version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Deploy Master Branch
          command: |
            -sudo apt-get update
            -sudo apt-get -qq install git-ftp
            -run: node .circleci/deploy.js
            -run: echo "WE'RE ONLINE"
workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master