version: 2
jobs:      
  deploy:
    docker:
      - image: circleci/php:7.1.5-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Deploy Staging Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "Deploying project ..."
            echo $(git status)
            run: npm install
            npx gulp build
            node .circleci/deploy.js
            
workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: staging