version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.1.5-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "Deploying project ..."
            echo $(git status)
            git ftp init --init-if-not-exist --user "sigephom" --passwd "Mr367774@" cwp.erpsigep.com.br

workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master